# Site
repository: cfcgoncalves/catiagoncalves
favicon: images/favicon.ico

version: 2

# Personal info
name: Cátia Gonçalves
title: Data Scientist
email: catiafcgoncalves@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: cfcgoncalves
linkedin_username: catiafgoncalves
# orcid_username: 0000-0001-5221-5458
googlescholar_username: vZ0FkNcAAAAJ

# About Section
# about_title: About Me
about_profile_image: images/jg2.jpg
about_content: |
  <p><b>Hello!</b> My name is Cátia Gonçalves.</p>
  <p>I am a Data Scientist with a background in Biology who has over 3 years experience in <mark>Python</mark>, and<mark>R</mark>.</p>
  <p>I bring solid experience in research, critical thinking, technical communication and writing combined with discipline, attention to detail and project management.</p>
  
content:
  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Mordern Resume Theme
        link: sproogen.github.io/modern-resume-theme
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          text.
        description: |
          TEXT.
      - layout: top-middle
        title: itsgoingto.be
        link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          TEXT.
        description: |
          TEXT.

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: PhD Candidate
        sub_title: University of Manchester 
        caption: September 2017 - June 2022
        description: |
          TEXT.

      - layout: left
        border: weak
        title: Graduate Teaching Assistant 
        sub_title: University of Manchester
        caption: September 2018 - July 2019
        description: |
          TEXT.

      - layout: left
        border: weak
        title: Pre-doctoral Researcher
        sub_title: Instituto de Investigação e Inovação em Saúde 
        caption: January 2017 - August 2017
        description: |
          TEXT.

      - layout: left
        border: weak
        title: MSc Candidate 
        sub_title: Instituto de Biologia Molecular e Celular
        caption: September 2015 - October 2016
        description: |
          TEXT.

  - title: Education
    layout: list
    content:
      - title: Manchester University
        sub_title: PhD in Molecular and Cell Biology
        caption: 2017 - 2022
        description: |
          TEXT.
      - title: Porto University
        sub_title: MSc in Molecular and Cell Biology
        caption: 2014 - 2016
        description: |
          TEXT.
      - title: Porto University
        sub_title: BSc in Biology
        caption: 2014 - 2016
        description: |
          TEXT.
         
  - title: Title
    layout: text
    content: | # this will include new lines to allow paragraphs
      TEXT.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
